apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: chaostoolkit
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80